Core:
  MAX_WORKERS: 10
  MAX_ASYNC_WORKERS: 10
  PROFILER_INTERVAL: 5
  PROFILER_SNAPSHOTS: 10
  LOGGING_LEVEL: "DEBUG"

Rag:
  RAG_HOST: "localhost"
  RAG_PORT: 8000
  N_RESULT:  5
  SENTENCE_TRANSFORMER_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  MISTRAL_API_KEY: "your_mistral_api_key"
  MISTRAL_MODEL: "mistral-7b"

Pyrogram:
  PYRO_TELEGRAM_API_ID: "your_api_id"
  PYRO_TELEGRAM_API_HASH: "your_api_hash"
  PYRO_TELEGRAM_HISTORY_LIMIT: 100

Mongo:
  USER: "your_mongo_user"
  PASSWORD: "your_mongo_password"
  HOST: "localhost"
  PORT: 27017
  DATABASE_NAME: "your_database_name"

Aiogram:
  TELEGRAM_TOKEN: "your_telegram_token"

